spring.application.name=bookapi

api.prefix = /api/v1

# PostgreSQL DB config
spring.datasource.url=jdbc:postgresql://localhost:5432/blinkistdb
spring.datasource.username=postgres
spring.datasource.password=levancci
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.allow_update_outside_transaction=false

spring.datasource.hikari.auto-commit=false

# Connection pool settings
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

# Enable database health check
management.health.db.enabled=true
